using System;
using MySqlConnector;
using System_Information_Group_1.Model;

namespace System_Information_Group_1.DAL;
/// <summary>
/// The data access layer in the system for the nurse table in the database. This class provides methods to retrieve nurse data based on person ID or nurse ID.
/// </summary>
public class NurseDal
{
    #region Methods    
    /// <summary>
    /// Gets the nurse with person identifier.
    /// </summary>
    /// <param name="id">The identifier.</param>
    /// <returns>the nurse with the person ID</returns>
    public Nurse GetNurseWithPersonId(int id)
    {
        using var connection = new MySqlConnection(Connection.ConnectionString());
        connection.Open();
        var query = "select * from nurse where person_id = @id;";
        using var command = new MySqlCommand(query, connection);
        command.Parameters.Add("@id", MySqlDbType.Int32).Value = id;
        using var reader = command.ExecuteReader();
        var nurseIdOrdinal = reader.GetOrdinal("nurse_id");
        var personIdOrdinal = reader.GetOrdinal("person_id");

        // this should only return one nurse since this ID is a primary key
        return createNurse(reader, nurseIdOrdinal, personIdOrdinal);
    }
    /// <summary>
    /// Gets the nurse with nurse identifier.
    /// </summary>
    /// <param name="id">The identifier.</param>
    /// <returns>The nurse with the specified nurse ID</returns>
    public Nurse GetNurseWithNurseId(int id)
    {
        using var connection = new MySqlConnection(Connection.ConnectionString());
        connection.Open();
        var query = "select * from nurse where nurse_id = @id;";
        using var command = new MySqlCommand(query, connection);
        command.Parameters.Add("@id", MySqlDbType.Int32).Value = id;
        using var reader = command.ExecuteReader();
        var personIdOrdinal = reader.GetOrdinal("person_id");
        var nurseIdOrdinal = reader.GetOrdinal("nurse_id");

        return createNurse(reader, nurseIdOrdinal, personIdOrdinal);
    }

    /// <summary>
    /// Creates a new nurse row for the given person id. The nurse_id is auto-generated by the database and returned inside the Nurse object.
    /// </summary>
    /// <param name="personId">Person identifier to link to the new nurse.</param>
    /// <returns>Newly created Nurse with generated nurse id.</returns>
    public Nurse CreateNurse(int personId)
    {
        using var connection = new MySqlConnection(Connection.ConnectionString());
        connection.Open();

        var insertQuery = "insert into nurse (person_id) values (@personId);";
        using (var command = new MySqlCommand(insertQuery, connection))
        {
            command.Parameters.Add("@personId", MySqlDbType.Int32).Value = personId;
            command.ExecuteNonQuery();
        }

        using var idCommand = new MySqlCommand("select last_insert_id();", connection);
        var inserted = System.Convert.ToInt32(idCommand.ExecuteScalar());

        return new Nurse(personId, inserted);
    }

    /// <summary>
    /// Updates the person_id for an existing nurse identified by nurse_id.
    /// </summary>
    /// <param name="nurseId">The nurse identifier.</param>
    /// <param name="newPersonId">The new person identifier to set.</param>
    /// <returns>True if a row was updated; otherwise false.</returns>
    public bool UpdateNursePersonId(int nurseId, int newPersonId)
    {
        using var connection = new MySqlConnection(Connection.ConnectionString());
        connection.Open();

        var updateQuery = "update nurse set person_id = @personId where nurse_id = @nurseId;";
        using var command = new MySqlCommand(updateQuery, connection);
        command.Parameters.Add("@personId", MySqlDbType.Int32).Value = newPersonId;
        command.Parameters.Add("@nurseId", MySqlDbType.Int32).Value = nurseId;

        var rows = command.ExecuteNonQuery();
        return rows > 0;
    }

    private static Nurse createNurse(MySqlDataReader reader, int nurseIdOrdinal, int personIdOrdinal)
    {
        return new Nurse(
            reader.GetFieldValueCheckNull<int>(personIdOrdinal),
            reader.GetFieldValueCheckNull<int>(nurseIdOrdinal)
        );
    }

    #endregion
}